spring.application.name=production-ready-features
spring.datasource.url=jdbc:mysql://localhost:3306/prod-ready-features?useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=9000
employeeService.base.url=http://localhost:8080/

#Logging Properties
logging.pattern.console=%d{dd-mm-yyyy hh:MM:ss} [%level] %c{1.} ----%m%n
logging.file.name=application.log

#Actuator Properties
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.author=Mayur Valte
info.app.env=DEV